services:
  server:
    image: ghcr.io/atvriders/multimon-rdp/server:latest
    restart: unless-stopped
    environment:
      PORT: "3000"
    ports:
      - "3000:3000"

  frontend:
    image: ghcr.io/atvriders/multimon-rdp/frontend:latest
    restart: unless-stopped
    ports:
      - "8080:80"
