services:
  server:
    image: ghcr.io/atvriders/multimon-rdp/server:latest
    restart: unless-stopped
    environment:
      PORT: "3001"
    ports:
      - "3001:3001"

  frontend:
    image: ghcr.io/atvriders/multimon-rdp/frontend:latest
    restart: unless-stopped
    ports:
      - "8080:80"
